default_platform :ios

platform :ios do

    lane :build do |options|

        ensure_git_status_clean
        ensure_git_branch(branch: "master")  

        increment_build_number

        commit_version_bump(message: "Release v1",
                            force:true)

    end

end